import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {useRouter} from 'next/router'
import { useState } from 'react'

export default function Home() {
  const router=useRouter()
  const handleClick = ()=>{
    router.push('/about?')
  }
  const [query, setQuery] = useState('')
  
  const setData=(event)=>{
  setQuery({
    [event.target.name]: event.target.value
  })
}
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home</h1>
        <button onClick={handleClick}>About</button>
        <div>
          <input
          type='text'
          name='search'
          onChange={setData}>
          </input>
          
          <button  type="button"
            onClick={() => {
            router.push({
            pathname: '/search?',
            query: { search: query },
        })
      }}>search</button>
          
        </div>
        </main>
    </div>
  )
}
